services:
  mongo:
    image: mongo:6
    container_name: timewell-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: timewell
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: timewell-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  localstack:
    image: localstack/localstack:3
    container_name: timewell-localstack
    restart: unless-stopped
    ports:
      - "4566:4566"
    environment:
      SERVICES: s3
      DEFAULT_REGION: us-east-1
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
    volumes:
      - ./scripts/localstack-init.sh:/etc/localstack/init/ready.d/init.sh
      - localstack_data:/var/lib/localstack

volumes:
  mongo_data:
  redis_data:
  localstack_data:
